# Generated by Django 5.0.2 on 2025-08-28 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guia_turistico', '0001_initial'),
        ('pontos_turisticos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacoteTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contato', models.CharField(max_length=11)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ImagemPorPacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='pacotes/')),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='pacote_turistico.pacoteturistico')),
            ],
        ),
        migrations.CreateModel(
            name='GuiaPorPacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guia_turistico.guiaturistico')),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacote_turistico.pacoteturistico')),
            ],
        ),
        migrations.CreateModel(
            name='PontosTuristicosPorPacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacote_turistico.pacoteturistico')),
                ('ponto_turistico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pontos_turisticos.pontosturisticos')),
            ],
        ),
    ]
