# Generated by Django 5.0.2 on 2025-08-28 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos_turisticos', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=100)),
                ('nome_usuario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PontosVisitadosPorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tempo_visita', models.IntegerField()),
                ('nota', models.IntegerField()),
                ('comentario', models.CharField(max_length=200)),
                ('ponto_turistico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pontos_turisticos.pontosturisticos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.users')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
