# Generated by Django 5.0.2 on 2025-08-28 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0002_users_pontosvisitadosporuser_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=11)),
                ('senha', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('comentario', models.CharField(max_length=200)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.users')),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guia_turistico.guiaturistico')),
            ],
        ),
    ]
