# Generated by Django 5.0.2 on 2025-08-28 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia_turistico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdiomaPorGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(choices=[('PT', 'Português'), ('EN', 'Inglês'), ('ES', 'Espanhol'), ('FR', 'Francês'), ('DE', 'Alemão')], max_length=2)),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiomas', to='guia_turistico.guiaturistico')),
            ],
        ),
        migrations.CreateModel(
            name='RedeSocialPorGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('tiktok', 'TikTok'), ('youtube', 'YouTube')], max_length=20)),
                ('url', models.CharField(max_length=255)),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes', to='guia_turistico.guiaturistico')),
            ],
        ),
    ]
